<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_2051026490.jpg" id="_10_5_622020d_1132928309060_862778_5751"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="UnexpectedException" refid="_9_5_f720368_1110473546674_917779_8249"/></annotatedElement><body humanName="Body" mode="s,e">An &lt;code&gt;UnexpectedException&lt;/code&gt; is thrown if the client of a
remote method call receives, as a result of the call, a checked
exception that is not among the checked exception types declared in the
&lt;code&gt;throws&lt;/code&gt; clause of the method in the remote interface.

@version 1.12, 12/19/03
@author  Roger Riggs
@since   JDK1.1
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_1555793073.jpg" mode="s,e" name="UnexpectedException" refid="_9_5_f720368_1110473546674_917779_8249"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="UnexpectedException" refid="_9_5_f720368_1110473546674_917779_8249"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>