<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928308630_716506_5407" refElementId="_10_5_622020d_1132928308630_716506_5407"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="FileLockInterruptionException" refElementId="_9_5_f720368_1110473546643_841379_7895" refid="_9_5_f720368_1110473546643_841379_7895"/></annotatedElement><body humanName="Body" mode="s,e">Checked exception received by a thread when another thread interrupts it
while it is waiting to acquire a file lock.  Before this exception is thrown
the interrupt status of the previously-blocked thread will have been set.

@version 1.9, 01/11/19
@since 1.4
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="FileLockInterruptionException" refElementId="_9_5_f720368_1110473546643_841379_7895" refid="_9_5_f720368_1110473546643_841379_7895"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="FileLockInterruptionException" refElementId="_9_5_f720368_1110473546643_841379_7895" refid="_9_5_f720368_1110473546643_841379_7895"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>