<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928316040_260039_10449" refElementId="_10_5_622020d_1132928316040_260039_10449"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="AccountNotFoundException" refElementId="_10_5_622020d_1132928316040_280190_10447" refid="_10_5_622020d_1132928316040_280190_10447"/></annotatedElement><body humanName="Body" mode="s,e">Signals that an account was not found.

&lt;p&gt; This exception may be thrown by a LoginModule if it is unable
to locate an account necessary to perform authentication.

@version 1.2, 12/19/03
@since 1.5
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="AccountNotFoundException" refElementId="_10_5_622020d_1132928316040_280190_10447" refid="_10_5_622020d_1132928316040_280190_10447"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="AccountNotFoundException" refElementId="_10_5_622020d_1132928316040_280190_10447" refid="_10_5_622020d_1132928316040_280190_10447"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>