<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928309060_509708_5753" refElementId="_10_5_622020d_1132928309060_509708_5753"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="UnknownHostException" refElementId="_9_5_f720368_1110473546674_499153_8251" refid="_9_5_f720368_1110473546674_499153_8251"/></annotatedElement><body humanName="Body" mode="s,e">An &lt;code&gt;UnknownHostException&lt;/code&gt; is thrown if a
&lt;code&gt;java.net.UnknownHostException&lt;/code&gt; occurs while creating
a connection to the remote host for a remote method call.

@version 1.13, 12/19/03
@since   JDK1.1
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="UnknownHostException" refElementId="_9_5_f720368_1110473546674_499153_8251" refid="_9_5_f720368_1110473546674_499153_8251"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="UnknownHostException" refElementId="_9_5_f720368_1110473546674_499153_8251" refid="_9_5_f720368_1110473546674_499153_8251"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>