<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928316040_645924_10446" refElementId="_10_5_622020d_1132928316040_645924_10446"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="AccountLockedException" refElementId="_10_5_622020d_1132928316040_911535_10444" refid="_10_5_622020d_1132928316040_911535_10444"/></annotatedElement><body humanName="Body" mode="s,e">Signals that an account was locked.

&lt;p&gt; This exception may be thrown by a LoginModule if it
determines that authentication is being attempted on a
locked account.

@version 1.2, 12/19/03
@since 1.5
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="AccountLockedException" refElementId="_10_5_622020d_1132928316040_911535_10444" refid="_10_5_622020d_1132928316040_911535_10444"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="AccountLockedException" refElementId="_10_5_622020d_1132928316040_911535_10444" refid="_10_5_622020d_1132928316040_911535_10444"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>