<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_2051026490.jpg" id="_10_5_622020d_1132928309040_521542_5712"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ConnectException" refid="_9_5_f720368_1110473546674_937157_8219"/></annotatedElement><body humanName="Body" mode="s,e">A &lt;code&gt;ConnectException&lt;/code&gt; is thrown if a connection is refused
to the remote host for a remote method call.

@version 1.13, 12/19/03
@author  Ann Wollrath
@since   JDK1.1
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_1555793073.jpg" mode="s,e" name="ConnectException" refid="_9_5_f720368_1110473546674_937157_8219"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ConnectException" refid="_9_5_f720368_1110473546674_937157_8219"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>